### PR TITLE
move indexing from Dash.jl

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
as stated in https://github.com/plotly/Dash.jl/pull/219#issuecomment-1660616422

### CODE REVIEW

**Review by etpinard — APPROVED** [review]
Fantastic. Thanks very much!

**Comment by etpinard** [comment]
I'll merge this, but I'll wait until https://github.com/plotly/DashBase.jl/pull/4 is done to release this PR along with https://github.com/plotly/DashBase.jl/pull/4 in DashBase `v0.3.0`

**Comment by BeastyBlacksmith** [comment]
> in DashBase `v0.3.0`

There are no breaking changes in any if those PRs, so this should be released as 0.2.1

If you were to make a breaking release, I'd vote for making that 1.0.0.

**Comment by etpinard** [comment]
From the perspective of DashBase.jl, you're absolutely right. We're just adding things here.

But, what would happen if we release DashBase `v0.2.1` off the current master, then users installing or updating Dash.jl would get DashBase `v0.2.1` along with Dash `v1.3.0` meaning that ` Base.getindex(component::Component, id::AbstractString)` would be defined in two places. Doesn't that lead to errors?

> If you were to make a breaking release, I'd vote for making that 1.0.0.

Yep, we can make the next DashBase release `v1.0.0`

**Comment by BeastyBlacksmith** [comment]
We'd need to test that precompilation does not break, but I'd think that those methods would just get overridden, which is not ideal, since you'd get the buggy version then.
On the other hand that is only an issue until the new Dash version is released. But then, if Dash is the only consumer of DashBase, making it 1.0 is also fine.

**Pull request merged**
